# Generated by Django 5.0.1 on 2024-04-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_watchlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
