# Generated by Django 5.0.1 on 2024-04-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listings_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
